### ISSUE TITLE
Add support for documenting multipart request parameters

### ISSUE THREAD

**Issue by mminella** [spring-projects/spring-restdocs#104]
While `RestDocumentationRequestBuilders` has support for file upload testing via the `RestDocumentationRequestBuilders#fileUpload`, additional parameters are not able to be documented due to the lack of support for multipart requests.  Below is an example of a request that would I'd like to see suported:

```
mockMvc.perform(fileUpload("/batch/files")
    .file(file).param("path", "/foo").accept(MediaType.APPLICATION_JSON))
```

**Comment by wilkinsona** [comment]
Multipart requests are already supported by the curl and HTTP request snippets (see https://github.com/spring-projects/spring-restdocs/issues/48). What's missing is support for documenting parameters.

**Comment by wilkinsona** [comment]
A better API is needed for this, but, somewhat bizarrely, you can already document the parameters using `queryParameters`:

```java
mockMvc.perform(fileUpload("/batch/files")
        .file("foo", new byte[] { 1, 2, 3, 4 })
        .param("path", "/foo")
        .accept(MediaType.APPLICATION_JSON))
        .andDo(document("foo",
                queryParameters(
                        parameterWithName("path").description("description"))));
}
```

The reason is that the query parameters snippet looks in the request's parameters map. That's where all parameters end up, whether they're specified using `param` or directly in the url.
