### ISSUE TITLE
Provide support for JSON field paths that use bracket notation

### ISSUE THREAD

**Issue by jrrickard** [spring-projects/spring-restdocs#131]
I'm trying to use spring-restdocs on a legacy project that returns a JSON object that looks something like:

{ 
   "license.mode" : "extended",
   .......
}

I don't have the luxury of fixing the JSON, so it would be nice to be able to specify a separator when building a path, maybe something like:

```
                .andDo(document("licensedetails",responseFields(
                        fieldWithPath("license.mode|subkey","|")
                                .type(JsonFieldType.STRING)
                                .description("The license mode of the service")
```

I'm working on a change for this for our use, will submit a PR if it's desired.

**Comment by wilkinsona** [comment]
Thanks for the offer of a PR for your custom separator change. The path syntax is intended to be (a subset of) JSON path so I think the right approach here is to add support for bracket notation (as described [here](http://goessner.net/articles/JsonPath/)), in addition to the existing support for dot notation. Ideally that should happen without having to indicate which notation is being used so that `fieldWithPath("foo.bar")` and `fieldWithPath("['foo']['bar']") are equivalent.

I'll see if I can get this into 1.0.0.RELEASE.

**Comment by jrrickard** [comment]
@wilkinsona I agree with the bracket notation and I actually abandoned the custom separator and was trying to implement that. If I get it working this afternoon I'll submit a PR for that.
