### ISSUE TITLE
ParameterDescriptor should allow optional() declaration

### ISSUE THREAD

**Issue by nebhale** [spring-projects/spring-restdocs#169]
Currently, the `ParameterDescriptor` does not allow an `optional()` descriptor.  This makes it difficulty to document parameters that are not required, and do not exist in the current example.  The `ParameterDescriptor` should be able to be declared optional.

**Comment by wilkinsona** [comment]
I thought this was going to be annoyingly hard to change due to the `ParameterDescriptor` being shared between path parameters and request parameters as optional path parameters seemed a bit strange. However, it would appear that [JAX-RS supports them](http://jersey.576304.n2.nabble.com/Optional-PathParam-is-it-possible-td4589195.html) so it makes sense for REST Docs to be able to document them as I don't want REST Docs to restrict people's API design unnecessarily, however strange I think it may be.

**Comment by adamdec** [comment]
Let me work on that if you do not mind.

**Comment by wilkinsona** [comment]
@adamdec How's it going?
