### ISSUE TITLE
If links() are documented the links field should be ignored

### ISSUE THREAD

**Issue by nebhale** [spring-projects/spring-restdocs#170]
Currently when documenting a HAL payload using `links()`, you are still required to always `.ignore()` the `_links` field.  As this documentation is typically close to one another, and most readers are smart enough to figure it out, the `_links` field should be ignored whenever `links()` are used.  It's probably reasonable to allow users to document `_links` if they chose, but the `fieldWithPath("_links").ignored()` should not be required.

**Comment by wilkinsona** [comment]
I'm not convinced that this is a good idea. I think it's too strong an opinion for REST Docs to take. I like being able to include a link from the payload documentation to the links documentation and the proposed change would allow me to forget to do that without the test failing. At an implementation level, I'm also not keen on the configuration or use of one snippet affecting the behaviour of another due to the coupling that it would introduce.

All that said, I'd still like it to be easier for you to do what you want without having to repeat `fieldWithPath("_links").ignored()`. Perhaps #168 is the answer? I'm open to any other suggestions too.

**Comment by nebhale** [comment]
#168 would overlap with this.

**Comment by wilkinsona** [comment]
Closing in favour of #168
