### ISSUE TITLE
RequestDocumentation.pathParameters ignores RestDocumentationMockMvcConfigurer

### ISSUE THREAD

**Issue by florind** [spring-projects/spring-restdocs#172]
I am configuring the URIs as described here: http://docs.spring.io/spring-restdocs/docs/current/reference/html5/#configuration-uris
I've observed that generating path parameters documentation using:
...pathParameters(parameterWithName("param").description("Description..."))...
results in a path-parameters.adoc snippet where the URI uses "localhost" instead of the specified one.

**Comment by wilkinsona** [comment]
The path parameters snippet uses the url template used to make the request as the title of the table. For example `get("a/b/{c}/{d}")` will result in the title being `a/b/{c}/d}`. Unless you're including localhost in that url template, I can't see how it's appearing in the snippet.

Can you please share an example that illustrates the problem you're seeing?

**Comment by wilkinsona** [comment]
The path parameters snippet uses the URLl template from the request as the title of the table. For example, if you call `get("a/b/{c}/{d}")` the title of the table will be `a/b/{c}/{d}`. Unless you're including `localhost` in that URL template I can't see how it's appearing in the snippet. I guess I must be missing something.

Can you please share a small sample that illustrates the problem that you're seeing?

**Comment by wilkinsona** [comment]
From a comment by @florind accidentally made on another issue:

> Example:

> Config:
```
this.mockMvc = MockMvcBuilders.webAppContextSetup(this.context)
        .apply(documentationConfiguration(this.restDocumentation).uris()
                .withScheme("https")
                .withHost("my-host.com")
                .withPort(443))
        .alwaysDo(this.document)
        .build();
```
> Code:
```
this.mockMvc.perform(get(serviceRootUrl + "/{policyId}", policyId)
        .header(HttpHeaders.AUTHORIZATION, authHeader.get(HttpHeaders.AUTHORIZATION)))
        .andExpect(status().isOk())
        .andDo(document("fetch-by-policyid",
                pathParameters(parameterWithName("policyId").description("Insurance policy id"))));
```
Results in the following path-parameters.adoc:
```
.http://localhost:64729/insurance/policies/{policyId}                                                                                      
|===                                                                                                                                       
|Parameter|Description                                                                                                                     
|policyId                                                                                                                                  
|Insurance policy id                                                                                                                        
|===                                                                                                                                                                
```
I don't have any customization for generating the path params. I might be doing something wrong though, can't figure what...

**Comment by wilkinsona** [comment]
@florind `serviceRootUrl` must be `http://localhost:64729/insurances/policies`. There's no need to include the scheme, host, or port; `/insurances/policies` is sufficient. You'll then get `/insurances/policies/{policyId}` appearing in the snippet.

**Comment by florind** [comment]
@wilkinsona thanks, it worked. I guess I didn't understand the underlying mechanism then... 
The code below uses localhost then generates (as expected) proper the *.adoc snippets, e.g. with https://my-host.com replacing the localhost equivalent:
```
        this.mockMvc.perform(get("http://localhost:8080/account/unknown-id")
                .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isNotFound());
```
Granted, it's not using the ```andDo(document``` construct and indeed the URL path omits the host&port which is actually nice. I guess it's a matter of consistency then between what gets generated by ```andDo(document...``` v  ```perform(get...```.

<sup>(Btw, MockMvcRestDocumentation.document requires an identifier that is used as the dir name when generating the snippet. Is there any way to reuse the name generated from the test method name? Sorry for overloading this issue)</sup>

**Comment by wilkinsona** [comment]
> I guess it's a matter of consistency then between what gets generated by andDo(document... v perform(get....

It's certainly unfortunate that it's inconsistent. The path parameter support captures whatever's passed into `get` and uses it as-is. Whereas, the `scheme`, `host`, and `port` configuration is only applied when an `HttpServletRequest` is involved.

It's certainly possible to change this behaviour so that the `scheme`, `host` and `port` are applied to whatever's passed to `get()`, but I'm reluctant to make the change as it may not suit everyone:

 - The most common usage of `get` is not to provide a scheme, host, or port at all. Always applying the configuration from `RestDocumentationMockMvcConfigurer` may not be what people want.
 - Applying the configuration from `RestDocumentationMockMvcConfigurer` to only replace (rather than add) a scheme, host, or port may be better but it still leaves a possible edge case where that's not the desired behaviour as, for whatever reason, a different scheme, host or port was being used deliberately.

> (Btw, MockMvcRestDocumentation.document requires an identifier that is used as the dir name when generating the snippet. Is there any way to reuse the name generated from the test method name? Sorry for overloading this issue)

Have you seen [the section in the reference documentation](http://docs.spring.io/spring-restdocs/docs/current/reference/html5/#documentating-your-api-parameterized-output-directories) about this? If that doesn't answer your question, please ask on Stack Overflow using the `spring-restdocs` tag.

**Comment by florind** [comment]
I am using RestTemplate together with Spring Rest Docs in my test suite, e.g. when I test a GET but I needed to create a resource first as I couldn't figure how to do mix together a post and a get within the same test. RestTemplate requires full URIs, hence the problem I've hit.
I'll try the parametrized {step} suggestion you linked above, it should be enough to get rid of the RestTemplate altogether.
Thanks!

**Comment by wilkinsona** [comment]
> I am using RestTemplate together with Spring Rest Docs in my test suite, e.g. when I test a GET but I needed to create a resource first as I couldn't figure how to do mix together a post and a get within the same test.

You can make multiple `MockMvc` calls. Just don't use `document` for the ones where you're setting stuff up. Also, rather than making a REST call to set things up, you may want to consider calling into the back end directly. Take a look at `ApiDocumentation` in the Spring HATEOAS sample for an example of this. It injects a few repositories and uses them to set stuff up that it wants to document.

**Comment by florind** [comment]
Indeed, works like a charm. Thanks @wilkinsona!
