### ISSUE TITLE
Problems with special chars

### ISSUE THREAD

**Issue by JohannesFluegel** [spring-projects/spring-restdocs#201]
I have written an issue in Stack Overflow: [Spring REST Docs: special characters are not shown correctly](http://stackoverflow.com/questions/35359141/spring-rest-docs-special-characters-are-not-shown-correctly). Andy Wilkinson has asked me to write a simple sample that reproduces the error. Here it is. Unfortunately it is not that simple because the _build.gradle_ contains unnecessary dependencies and spring security is used.

1. Download and unzip 
[spring-rest-docs-special-chars-problem.zip](https://github.com/spring-projects/spring-restdocs/files/130416/spring-rest-docs-special-chars-problem.zip)
2. In Eclipse create a new Gradle Project.
3. Overwrite your _build.gradle_ with the one from the zip file.
4. Generate _/src/main/java/application/Application.java_.
5. Generate _/src/main/java/controller/Controller.java_.
6. Generate _/src/main/java/dtos/Pojo.java_.
7. Generate _/src/test/java/controller/IntegrationTest.java_.
8. Generate _/src/docs/asciidoc/index.adoc_.
9. Run in Gradle _clean build_
10. Load _/build/docs/html5/index.html_ and check the result.

**Comment by wilkinsona** [comment]
Thanks for taking the time to provide a sample. By default all of the special characters appear correctly for me. I'm running your tests on OS X. My shell's language is `en_GB.UTF-8` and `Charset.defaultCharset()` return `UTF-8`.

If I set the `file.encoding` system property to `Cp1252` (the default on Windows, I believe), the special characters get corrupted. This gives me something to investigate.

In the meantime, if you're running in an environment where UTF-8 isn't the default encoding, can you please try setting the `file.encoding` system property. One way to do so is to configure it in your `build.gradle`:

```
test {
    outputs.dir snippetsDir
    systemProperty 'file.encoding', 'UTF8'
}
```

**Comment by JohannesFluegel** [comment]
Hi Andy, 

after setting 

> systemProperty 'file.encoding', 'UTF8'

the bug does not occur anymore and all works fine. 

What is strange: all my source files are UTF-8 encoded. `Charset.defaultCharset()` returns `UTF-8`, too.

**Comment by wilkinsona** [comment]
> Charset.defaultCharset() returns UTF-8, too.

The default charset is UTF-8 even without setting the `file.encoding` system property? If so, that is indeed strange.

One place where it's going wrong is when `OperationRequest.getContentAsString()` or `OperationResponse.getContentAsString` is called. The curl snippet calls this method, for example. The `getContentAsString()` method uses the `Content-Type` header to determine the charset of its content. If that header is not set, it falls back to using the JVM's default charset. This leads to corruption of the text.

This means that, rather than setting `file.encoding` you should also be able to fix the problem by specifying the charset when you configure the content type in your tests. For example:

```
.perform(post("/echo-plain-string").content("Größe").contentType("text/plain;charset=UTF-8"))
```

Interestingly, a similar change doesn't completely resolve the problem in the POJO case. It corrects the problem in all of the standard snippets, but breaks the pretty-printed snippets. That's a bug in REST Docs as the pretty printing logic isn't honouring the charset correctly.

**Comment by JohannesFluegel** [comment]
I have deleted `systemProperty 'file.encoding', 'UTF8'` from my `build.gradle` and then I get the properties:

    os.name=Windows 7
    sun.jnu.encoding=Cp1252
    file.encoding=UTF-8
    ...

Is it possible that `sun.jnu.encoding` is used anywhere?

**Comment by wilkinsona** [comment]
> Is it possible that sun.jnu.encoding is used anywhere?

Spring REST Docs doesn't use it anywhere directly. I hadn't heard of it before but some reading would suggest that it's used for command-line arguments. I don't think it'll be having an effect here.

**Comment by wilkinsona** [comment]
@JohannesFluegel Thanks again for putting together a sample project. I've fixed the problem with pretty printing that I described above (see #202) and I've added a note to the documentation about how the charset is used when converting a request or response's content to a string.

To summarise, the avoid the problems that you saw your options are:

- Set the `file.encoding` system property
- Specify the charset as part of the request content type
