### ISSUE TITLE
Expose snippet descriptors

### ISSUE THREAD

**Issue by psamsotha** [spring-projects/spring-restdocs#224]
I was wondering if it would be a problem to expose the snippet descriptors. My current use case is as follows.

I am creating a UI, for which I am writing a custom snippet. The UI is not to be a replacement for "real" documentation, but should compliment it. So the user should still write their normal snippets used for documentation. The problem is, I need those same descriptors for use with my custom snippet. My snippet would look something like

```java
class MySnippet implements Snippet {
    ...
    public MySnippet requestParameters(RequestParametersSnippet snippet) {
        this.requestParameterDescriptors = snippet.getParameterDescriptors();
        return this;
    }

    public MySnippet headerParameters(HeadersSnippet snippet) {
        this.headerDescriptors = snippet.getHeaderDescriptors();
        return this;
    }
}
```

And its usage, something like

```java
final RequestParametersSnippet requestParametersSnippet = requestParameters(
        parameterWithName("limit").description("limit the number of results"));
final RequestHeadersSnippet headersSnippet = requestHeaders(
        headerWithName("X-Custom-Header").description("some random custom header"));
       
given().port(this.port).filter(documentationConfiguration(this.restDocumentation))
        .filter(document("...").snippets(
                requestParametersSnippet, 
                headersSnippet,
                mySnippet()
                        .requestParameters(requestParametersSnippet)
                        .requestHeaders(headersSnippet)
                ))...
```

So you can see I am reusing the snippets. The problem is the descriptors access is `protected`, so I can't do `snippet.getHeaderDescriptors()`. 

What I want to avoid is having to hold reference to a bunch of descriptors, in order to reuse them. I can live with holding references to the snippets, as it doesn't look as messy, even though I don't even really need the entire snippet.

What are you thoughts on this?

**Comment by wilkinsona** [comment]
I'm not keen (at the moment, anyway) to add this.

I don't like the API where request parameter descriptors are being configured via an argument that takes a `Snippet`. I considered adding a similar method when adding support for reusing snippets, but I rejected it in the end as I think it hurts the readability of the code. To me, it's not clear that it's only the descriptors that will be used when an entire snippet is passed in.

While it may be messier (I'm not sure that I agree), I think the intent is much clearer if the descriptors are configured by passing in some descriptors rather than a snippet that happens to contain some descriptors.

Perhaps we can take a step back and find another way to solve your problem?

**Comment by psamsotha** [comment]
Yeah, you're right about the intent being clearer. I guess I kind of had my priorities mixed up :-). Thanks for your input.
