### ISSUE TITLE
Automatically escape characters that break Asciidoctor and Markdown formatting

### ISSUE THREAD

**Issue by varpa89** [spring-projects/spring-restdocs#232]
I have a field with validation pattern like this
```
@Pattern(regexp = "^$|^[0-9]{12}$")
private String inn;
```

When I generate the documentation for request-fields with ConstrainedFields I have this output:

```
|inn
|String
|ИНН
|Must match the regular expression '^$|^[0-9]{12}$'
```

As you can see there is '|' symbol which breaks the layout from [this](https://github.com/spring-projects/spring-restdocs/blob/v1.1.0.RC1/samples/rest-notes-spring-hateoas/src/test/resources/org/springframework/restdocs/templates/request-fields.snippet)

ext.springRestDocsVersion = '1.1.0.RC1'

**Comment by andysworkshop** [comment]
I've also hit this one. Easy to reproduce.

**Comment by wilkinsona** [comment]
A workaround is to escape the `|` in your test before you set the attribute on the descriptor. REST Docs should really do that for you, though.

**Comment by wilkinsona** [comment]
Providing some out-of-the-box configuration of an [`Escaper`](https://github.com/samskivert/jmustache#user-defined-escaping-rules) looks to be the most elegant way to implement this.

**Comment by wilkinsona** [comment]
Asciidoctor's straightforward. `|` can always be replaced with `{vbar}` and it'll do the right thing.

As ever, Markdown is more complicated. `|` messes up tables, but only if it isn't within back ticks. When it's not, and only when it's not, within back ticks it can be replaced with `&#124;`. If it's replaced when it's within backticks you end up with the literal `&#124;` rather than `|`. Without getting into parsing the Markdown (which I really don't want to do), it's impossible to know for certain when a `|` needs to be replaced and when it does not.

I think Markdown's limitations can be avoided by changing the message for the `@Pattern` constraint to enclose the regular expression in backticks. That'll work for Markdown without adversely affecting Asciidoctor. Arguably, it'll also make the pattern easier to read (see #230).

**Comment by wilkinsona** [comment]
I spoke to soon. Always replacing `|` with `{vbar}` in Asciidoctor breaks the HTTPie snippet which uses `|`. Using `{vbar}`, the HTML ends up containing something like this:

```
$ echo 'content' {vbar} http POST 'http://localhost:8080/' 'Accept:application/json'
```

When it should be:

```
$ echo 'content' | http POST 'http://localhost:8080/' 'Accept:application/json'
```

Looks like it's going to be necessary to provide a JMustache lambda that can then be used in the templates for table cell content where escaping is definitely required.

**Comment by varpa89** [comment]
Do I need fix template or another code after upgrade to 1.1.0.RELEASE?
Template
|===
```
|Path|Type|Description|Constraints

{{#fields}}
|{{path}}
|{{type}}
|{{description}}
|{{constraints}}

{{/fields}}
|===
```

I still have the same output
```
|inn
|String
|ИНН
|Must match the regular expression '^$|^[0-9]{12}$'
```

**Comment by wilkinsona** [comment]
If you're using a custom template, then you need to wrap anything that you want to be escaped to use the `tableCellContent` lambda. For example:

```
|===
|Path|Type|Description|Constraints

{{#fields}}
|{{#tableCellContent}}`{{path}}`{{/tableCellContent}}
|{{#tableCellContent}}`{{type}}`{{/tableCellContent}}
|{{#tableCellContent}}{{description}}{{/tableCellContent}}
|{{#tableCellContent}}{{constraints}}{{/tableCellContent}}

{{/fields}}
|===
```

**Comment by wilkinsona** [comment]
I've opened #251 to document it

**Comment by varpa89** [comment]
perfecto! thank you very much!
