### ISSUE TITLE
Limitation for response data

### ISSUE THREAD

**Issue by varpa89** [spring-projects/spring-restdocs#236]
Some requests return array of data items and usually there is more data than we should to put in our documentation because it will be unreadable and heavy documentation.

Is it possible to reduce response data if the method does not allow to use limit parameter?

In addition it will be great if spring-restdocs could generate 'View result' blocks like [this](http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#images)

**Comment by wilkinsona** [comment]
There are a couple of existing options that might work here:

1. Mock something out in the service to limit that amount of data that's returned. 
2. Use a preprocessor to change the response prior to it being documented. There a bit of information in the documentation about [writing your own preprocessor](http://docs.spring.io/spring-restdocs/docs/current/reference/html5/#customizing-requests-and-responses-preprocessors-writing-your-own)

Does either of these fit your needs?

The "View result" blocks are an Asciidoctor thing, rather than a REST Docs thing. You can learn more about them [here](http://discuss.asciidoctor.org/Using-quot-View-Results-quot-boxes-as-in-Asciidoctor-Syntax-Quick-Reference-td1333.html) and in the pages linked to from that discussion.

**Comment by varpa89** [comment]
Thanks for helping. I think this options are ok. I'l try to use one of them and write tutorial =)

**Comment by wilkinsona** [comment]
Thanks for following up
