### ISSUE TITLE
Custom Host header is not included in cURL and HTTPie request snippets

### ISSUE THREAD

**Issue by mle-enso** [spring-projects/spring-restdocs#258]
Due to a rather uncommon domain design of our platform we depend at least for fallback reasons on host header information.

While documenting of host header information is no problem like shown here…
```java
given(getRequestSpec())
                .config(RestAssuredConfig.config().redirect(RedirectConfig.redirectConfig().followRedirects(false)))
                .when()
                .filter(document("host-header",
                        requestHeaders(
                                headerWithName("Host").description("An alternative way to point to a sub-domain"))
                        ))
                .header("Host", "www.host.tld")
                .get("/endpoint")
                .then()
                .statusCode(301);
```
…the host header documentation exists in http-request.adoc but **not** in curl-request.adoc.

I've found `org.springframework.restdocs.cli.CliOperationRequest` which explicitly excludes the host header from the documented CLI (curl) output.

The question is: Is there any possibility to configure the headers which should be excluded from being documented in curl-request.adoc?

**Comment by wilkinsona** [comment]
The `Host` header is excluded from the curl request snippet as curl will set it automatically. I guess you are "spoofing" the `Host` header so that it has a value other than the host to which the request is sent? If that's the case, the snippet could be made a bit smarter so that it includes the `Host` header only if its value is different to what curl would set automatically.

**Comment by mle-enso** [comment]
Thanks for your response. Your guess was correct and your proposal would meet exactly our requirements.
