### ISSUE TITLE
Provide a convention-based approach for determining the output directory

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-restdocs#297]
It'd be nice not to have to configure the snippet output directory, and certainly not in two places (build script and the tests) as is currently required. The former is used to tell Asciidoctor from where the snippets can be included. The latter is used to tell the tests where to write the snippets.

The output directory varies depending on which build system is in use. For Maven it's typically `target/generated-snippets`. For Gradle it's typically `build/generated-snippets`. We can determine which build system is in use by looking for a `pom.xml` in the current directory. If one is found then Maven is in use, otherwise assume that it's a Gradle build.

Making the tests use this convention-based output directory by default is straightforward. It's a simple change to `ManualRestDocumentation` and the wrappers that use it as a delegate to make the output directory optional. When one is not specified, the convention-based default should be used.

Getting the convention-based default into Asciidoctor isn't quite so straightforward. The current plan is to provide a custom Asciidoctor macro for snippet inclusion. This macro will include the logic for determining the output directory by convention. Rather than including a snippet like this:

```
include::{snippets}/error-example/http-response.adoc[]
```

It would be included like this instead:

```
snippet::error-example/http-response.adoc[]
```

The custom `snippet` macro will behave exactly like the `include` macro but will prefix the path with the automatically determined output directory.

**Comment by meistermeier** [comment]
This is a really great idea for more convenience. Has there been any work on this issue? I would like to help and hack (especially but not only the asciidoctor part) ;)

**Comment by wilkinsona** [comment]
Nothing of any real substance. A contribution would be most welcome.

**Comment by meistermeier** [comment]
Here is my (not so small) change to get a default output directory handling. I did not extend or provide a new sample since I won't change too much before getting a review ;)
To use the new macro you have to include it in maven/gradle as a dependency:

    <plugin>
        <groupId>org.asciidoctor</groupId>
        ....
        <dependencies>
            <dependency>
	        <groupId>org.springframework.restdocs</groupId>
	        <artifactId>spring-restdocs-asciidoctor-extensions</artifactId>
	        <version>1.2.0.BUILD-SNAPSHOT</version>
            </dependency>
        </dependencies>
    ....
    </plugin>

or gradle

    dependencies {
        asciidoctor 'org.springframework.restdocs:spring-restdocs-asciidoctor-extensions:1.2.0.BUILD-SNAPSHOT'
    }

**Comment by wilkinsona** [comment]
I've just realised that the proposed `snippet` macro is overkill. All that's actually needed is a preprocessor that automatically sets the `snippets` attribute if it hasn't already been set by the user. 

I have this working based on top of the work done by @meistermeier in #310.

**Comment by wilkinsona** [comment]
I believe the current implementation will work fine with Gradle, but there may be a problem with Maven. Thanks for @meistermeier for pointing out the possible problem.

The logic for identifying that it's a Maven build and correctly determining the relative path from the docdir to the generated snippets relies on the working directory being the root of the Maven module that's being built. Need to double-check that is the case with a multi-module build and a build that's launched from another directory.

**Comment by meistermeier** [comment]
The problem also exists in gradle projects. I tried to compile a project simple gradle project from its parent folder and got a warning saying: 'include file not found'.

**Comment by wilkinsona** [comment]
@meistermeier Interesting, thank you. That suggests that the Asciidoctor Gradle plugin is setting the `projectdir` attribute incorrectly. In the root of the REST Docs repository I've tried both `gradle -b samples/rest-assured/build.gradle asciidoctor` and `samples/rest-assured/gradlew -b samples/rest-assured/build.gradle asciidoctor`. The includes worked in both cases. Can you share some more details of how to reproduce the problem please?

**Comment by wilkinsona** [comment]
Maven definitely is broken. All of the includes fail when this command is run: `mvn -f samples/rest-notes-spring-data-rest/pom.xml package`.

**Comment by meistermeier** [comment]
Ok, your 99% right, that gradle works ;) The problem just appears if you run the `gradle(w)` command in a maven directory. It may not be very common but I started with a maven based test project and added the gradle project in a subdirectory because I just wanted to have an additional test module 😄
Related code:
https://github.com/spring-projects/spring-restdocs/blob/c13b7d03f5f6fa2d1b21e5ca6ff095a20b525415/spring-restdocs-asciidoctor/src/main/java/org/springframework/restdocs/asciidoctor/SnippetsDirectoryResolver.java#L40

**Comment by wilkinsona** [comment]
😄 A bit of an edge case, but one that's worth avoiding if possible. And I think I've managed to do that in the latest commit. The resolver now looks for the `maven.home` system property to determine that Maven's being used. Rather that using the working directory to locate the  `pom.xml` it now searches up the directory hierarchy from the `docdir`.

**Comment by meistermeier** [comment]
Yesterday I had a chat with @robertpanzer about the possibilities to fix
the current bug/misbehaviour. If we stick with the current version of
asciidoctorj we cannot achieve:
1. Other output format / backend support than HTML because we have to
convert the file in place and add the output as raw (HTML) content to the
including surrounding -> Basically we will get HTML output in a PDF file ;)
This will be resolved in asciidoctorj 1.6 (no release date planned): With
this version it is possible to pass asciidoctor content back to the
including block without getting a generated enclosure (this is the reason
why I use the "pass style" for including in the current version).

2. We can determine the 'docfile' only with version 1.5.4.1. No problem to
update my dependency in the extensions module but the asciidoctor maven
plugin currently depends on 1.5.3.2 that throws an exception at runtime.

I was also thinking about this approach when I evaluated the different kind
of processors. I think it should also work with the current asciidoctorj
version required by the plugin since you get another process method
signature that also holds the document. Another benefit is that we don't
have to care about the rendering process and the output for the requested
backend will be served by asciidoctor. The only downside is that you will
still have to write the property placeholder in the include directive.
I think it is better to do a small step in the convenient direction than
dropping this approach and keep the users fighting with redundant and
error-prone "string maintenance" ;)

2016-10-21 19:07 GMT+02:00 Andy Wilkinson <notifications@github.com>:

**Comment by wilkinsona** [comment]
@meistermeier Thanks for chatting with @robertpanzer, however I don't think we have a bug/misbehaviour any more. As I [described above](https://github.com/spring-projects/spring-restdocs/issues/297#issuecomment-255554311), I believe that https://github.com/spring-projects/spring-restdocs/commit/49596df0f3b59cd22329f70ff0b7f07ebc3ebf07 has fixed the problem.

**Comment by meistermeier** [comment]
Wow...just wow. This answer was not intended ;) It's the mail version of https://github.com/spring-projects/spring-restdocs/pull/310#issuecomment-255516500 that got lost on the "Dyn-DDOS-Day". At least I thought it was lost and wrote the comment on the PR the day after. Sorry for confusion ;)

**Comment by wilkinsona** [comment]
No problem. The IoT has a lot to answer for!
