### ISSUE TITLE
To keep from printing the null attributes in JSON snippets.

### ISSUE THREAD

**Issue by syedwasimali** [spring-projects/spring-restdocs#333]
Hi, 

For my Spring Boot project, the Jackson JSON config JsonInclude.Include.NON_NULL is enforced as a global setting. The RESTDocs prettyprint() pre-processor takes care of the pretty printing, but prints all JSON attributes including attributes that are set to null. It is intriguing to find the ObjectMapper in  RESTDocs code to be permanently fixed: 

private final ObjectMapper objectMapper = new ObjectMapper()
				.configure(SerializationFeature.INDENT_OUTPUT, true);

		@Override
		public byte[] prettyPrint(byte[] original) throws IOException {
			return this.objectMapper
					.writeValueAsBytes(this.objectMapper.readTree(original));
		}

To be able to refer the application configured ObjectMapper here would have been ideal, I think. What other alternatives do I have? 

While looking at the documentation, I ran into "ignored()". I thought that perhaps I should try to  selectively ignore the JSON attributes using "ignored()", though I don't think it is working the way it was meant to. It is possible I am missing a detail or two that is getting in the way.

I have put together a simple example (https://github.com/syedwasimali/restdocs-test.git) with a couple of tests to show the issues above. Will appreciate any feedback in the regard.

thanks,

-Syed

**Comment by wilkinsona** [comment]
As shown by the code that you've shown above, the pretty printer simply takes the original JSON reads it in and writes it back out again. The round-tripping pretty prints the JSON while leaving it semantically identical to the original JSON. If it includes null attributes then that's because the original JSON produced by the service that you're documenting included null attributes.

The problem is that you've set up `MockMvc` using `standaloneSetup`. That means that your service knows nothing about your customisation of Jackson so the null attributes are still included in the JSON. You can avoid the problem either by using `webAppContextSetup` or by customizing the HTTP message converters using `setMessageConverters`.

Generally speaking, I would recommend using `webAppContextSetup` with REST Docs. If you use `standaloneSetup` you have to take care to tune the configuration so that the matches the configuration of your whole app. Any differences can lead to inaccurate documentation as shown here.

Marking a field as ignored simply stops it from appearing in the request or response fields snippet. This is described in [this section](http://docs.spring.io/spring-restdocs/docs/current/reference/html5/#documenting-your-api-request-response-payloads) of the documentation.

**Comment by syedwasimali** [comment]
Agreed. Thanks for the recommendations. Made the changes to the sample project.
