### ISSUE TITLE
Optional fields are resulting in test failures if not present in the request payload and the type hasn't been provided

### ISSUE THREAD

**Issue by vicusbass** [spring-projects/spring-restdocs#374]
If a field is marked as optional, the tests are still failing if the field is not present in the payload:
`org.springframework.restdocs.payload.FieldTypeRequiredException: Cannot determine the type of the field 'xxxx' as it is not present in the payload. Please provide a type using FieldDescriptor.type(Object type).`

This is related to [#289](https://github.com/spring-projects/spring-restdocs/issues/289), the fix is actually only checking for ignored fields, not for optional as well.

**Comment by wilkinsona** [comment]
This is working as designed. Marking a field as optional indicates that it may or may not appear in the payload but that it should appear in the documentation. If the field isn't present in the payload then you need to tell REST Docs the field's type so that it can be documented. As indicated in the exception message, you need to call `FieldDescriptor.type(Object)`.
