### ISSUE TITLE
Cannot ignore undocumented fields passed to .andWithPrefix()

### ISSUE THREAD

**Issue by micheleb** [spring-projects/spring-restdocs#400]
Using `relaxedResponseFields()` has no effect on the fields passed to the following `andWithPrefix()`, as `ignoreUndocumentedFields` is set to `false` by default in the `ResponseFieldsSnippet` constructor used by `andWithPrefix()`, and there doesn't seem to be a way to tell restdocs to ignore the nested fields, too.

An additional method like `andWithPrefix(String pathPrefix, boolean ignoreUndocumentedField, FieldDescriptor... additionalDescriptors)` would be great to have!

**Comment by wilkinsona** [comment]
Rather than adding a new method, I think it's actually a bug that calling `andWithPrefix(String, FieldDescriptor...)` doesn't return a snippet that ignores undocumented fields. That will affect both the original snippets descriptors and those added via `andWithPrefix`. I think this should be fixed by making the `andWithPrefix` methods pass the `ignoreUndocumentedFields` setting of the original snippet into the new snippet that combines the descriptors.
