### ISSUE TITLE
Handle multiple requests in the same test

### ISSUE THREAD

**Issue by Raibaz** [spring-projects/spring-restdocs#412]
I have a test doing roughly the following:

```
mockMvc.perform(delete("/api/foo/")
        .accept(MediaType.APPLICATION_JSON_VALUE)
        .contentType(MediaType.APPLICATION_JSON_VALUE)
        .content(objectMapper.writeValueAsBytes(body)))
.andExpect(status().isOk())
.andDo(restDocumentationResultHandler.document());

mockMvc.perform(get("/api/foo").accept(MediaType.APPLICATION_JSON_VALUE))
.andExpect(status().isOk())
.andExpect(jsonPath("$").isArray())
.andExpect(jsonPath("$").value(hasSize(0)));
```

Although the call to `document` is performed on the `delete` request, in the snippets directory my `http-request.adoc` for this test contains the `get` request, probably because it's the last one being performed.

I know that testing that the deletion actually happens should not belong in testing the web interface, also because it's already being tested for the service containing the business logic for the deletion, so it's not a big deal, but am I correct in expecting that the .adoc file should contain the details of the requests i am calling `document` on?

**Comment by wilkinsona** [comment]
It's impossible to say for sure without seeing how you've configured `MockMvc`, but I suspect that your expectation is incorrect. I'd guess that you have a `restDocumentationResultHandler` configured in some `alwaysDo` configuration so any Mock MVC call will be documented. You may want to use `{step}` so that multiple calls in the same test generate their snippets in different locations.

Some what related, your call to `restDocumentationResultHandler.document()` is strange as it's intended to create a new `RestDocumentationResultHandler` that will document additional snippets and you haven't passed any in.

**Comment by wilkinsona** [comment]
I'm going to close this one. If you have any follow up questions, please ask on Stack Overflow. It's a much better place for this sort of question.
