### ISSUE TITLE
Mustache Template missing in sources

### ISSUE THREAD

**Issue by filiphr** [spring-projects/spring-restdocs#417]
Maybe it is on purpose, but the `org.springframework.restdocs.mustache.Template` sources are missing in the sources of `spring-restdocs`. I saw that the `class` files are included [here](https://github.com/spring-projects/spring-restdocs/blob/master/spring-restdocs-core/build.gradle#L9).

I think that the Mustaches template classes should also include the sources as part of the `spring-restdocs` sources distribution.

**Comment by wilkinsona** [comment]
I agree that would be nice, but I don't believe it's possible. The JMustache classes are [repackaged](https://github.com/spring-projects/spring-restdocs/blob/645a60a7879f8ea2783e219eace3cd8e570e9218/spring-restdocs-core/build.gradle#L9-L25) to avoid class path conflicts. The repackaging works on the byte code rather than the source so there's no source that matches the repackaged classes.

**Comment by filiphr** [comment]
I think it is possible, in a similar way as you are repacking the classes the sources could be done (I think 😄 ).

If you are accepting PRs for this, I can try and have a look at it.

**Comment by wilkinsona** [comment]
A pull request would be welcome if you have the time. I took a quick look when you raised the issue and I don't think the jar jar Ant task supports rewriting the source. Fixing this, and being certain that the source matches the repackaged byte code might be rather involved.

**Comment by filiphr** [comment]
Yes you are actually right. The byte code is being changed. I'll have a look at it when I have the time. An alternative way would be to pull in as sources what you need to the package changes and compile that. I know that it is just nice to have
