### ISSUE TITLE
NullPointerException with WebTestClient when base URL has not been configured

### ISSUE THREAD

**Issue by jntakpe** [spring-projects/spring-restdocs#461]
Using the new Spring 5 webflux with webtestclient, an NullPointerException occurs when documenting a simple REST endpoints.

You can reproduce the issue using [this project]( https://github.com/jntakpe/webflux-bug-report).

The stacktrace : 
![restdocs_npe](https://user-images.githubusercontent.com/3605418/32994277-2fe89bda-cd65-11e7-9334-51e3b8437023.png)

**Comment by wilkinsona** [comment]
Thanks for the bug report and, in particular, for providing a sample. The REST Docs' `WebTestClient` is incorrectly assuming that the request URL will always have a host. Instead of making that assumption it should apply a default scheme (http), host (localhost), and port (8080) when they're not available. In the meantime, you can avoid the problem by configuring the base URL when you configure your `WebTestClient`. For example, the following change sets the base URL to `https://api.example.com`:

```diff
diff --git a/src/test/kotlin/com/github/jntakpe/webfluxbugreport/WebfluxBugReportApplicationTests.kt b/src/test/kotlin/com/github/jntakpe/webfluxbugreport/WebfluxBugReportApplicationTests.kt
index eb0d4e6..70c2d78 100644
--- a/src/test/kotlin/com/github/jntakpe/webfluxbugreport/WebfluxBugReportApplicationTests.kt
+++ b/src/test/kotlin/com/github/jntakpe/webfluxbugreport/WebfluxBugReportApplicationTests.kt
@@ -33,6 +33,7 @@ class WebfluxBugReportApplicationTests {
     fun beforeEach(context: ReactiveWebApplicationContext, restDocumentation: RestDocumentationContextProvider) {
         webTestClient = WebTestClient.bindToApplicationContext(context)
                 .configureClient()
+                .baseUrl("https://api.example.com")
                 .filter(documentationConfiguration(restDocumentation))
                 .build()
     }
```

**Comment by jntakpe** [comment]
Thanks a lot for the super fast fix and workaround
