### ISSUE TITLE
No possibility to add custom RequestConverter 

### ISSUE THREAD

**Issue by SergeyPirogov** [spring-projects/spring-restdocs#544]
There is no possibility to add custom request and response convertors. Default MockMvcRequestConverter and MockMvcResponseConverter have package private access. Is there any possibility to change this?

https://github.com/spring-projects/spring-restdocs/blob/aad07f0ce696fcd41a84cd0463acc85c8effd07d/spring-restdocs-mockmvc/src/main/java/org/springframework/restdocs/mockmvc/MockMvcRestDocumentation.java#L65-L69

**Comment by wilkinsona** [comment]
> Default MockMvcRequestConverter and MockMvcResponseConverter have package private access. Is there any possibility to change this?

Not without a compelling reason. Those classes are package-private as they are an implementation detail.

> Method GET is implicitly hardcoded for request converter

The check for `GET` there is only for determining the query string which has a knock-on effect on determining the request's URI.

Can you please describe the problem that you are facing rather than proposing a solution?

**Comment by wilkinsona** [comment]
Closing due to the lack of the requested feedback.
