### ISSUE TITLE
Add type support for ParameterDescriptor

### ISSUE THREAD

**Issue by RomanCht** [spring-projects/spring-restdocs#616]
As of now you can't set type for parameter descriptors (path and request parameters).
This affects RequestParametersSnippet and PathParametersSnippet.

Instead of simple
`parameterWithName("age").type(int.class)`

you need to add custom attribute:
`parameterWithName("age").attributes(key("type").value("int"))`

Plus you need to modify path-parameters and request-parameters default snippet Mustache templates to have type column, e.g.:
```
.+{{path}}+
|===
|Parameter|Type|Description
{{#parameters}}
|{{#tableCellContent}}`+{{name}}+`{{/tableCellContent}}
|{{#tableCellContent}}`+{{type}}+`{{/tableCellContent}}
|{{#tableCellContent}}{{description}}{{/tableCellContent}}
{{/parameters}}
|===
```
Was it intentional to not have support of type for path and request parameters? M.b. it'll be better to have such feature?

**Comment by wilkinsona** [comment]
It was intentional.

Unlike JSON, there's no type information in a URI's path and request parameters. In Java terms, they are all strings that may then be coerced to a particular type. However, that coercion is an implementation detail of the API that's being documented. I would discourage you from using something like `int.class` to document a type as `int.class` is JVM specific and should not be relevant to the clients of an API that they access over HTTP.

As you've noted, there is sufficient flexibility in REST Docs to allow you to document the type if you wish to do so. It isn't something that I want to encourage so I don't want to make it a first-class part of the API. Thanks anyway for the suggestion.
