### ISSUE TITLE
Are There Examples Of Custom CSS?

### ISSUE THREAD

**Issue by opticyclic** [spring-projects/spring-restdocs#618]
Are there any examples of using Spring REST Docs with a custom css?

Every blog or project on GitHub I see seems to use the defaults.

**Comment by wilkinsona** [comment]
Not that I am aware of, specifically for REST Docs. Customizing the CSS is really an Asciidoctor (or Markdown) matter rather than a REST Docs matter. You can learn more about the Asciidoctor side of things in its [reference documentation](https://asciidoctor.org/docs/produce-custom-themes-using-asciidoctor-stylesheet-factory/).
