### ISSUE TITLE
Not working with formlogin?

### ISSUE THREAD

**Issue by ValtteriL** [spring-projects/spring-restdocs#655]
I cannot get REST Docs to work with formlogin. This is my code:
```

@RunWith(SpringRunner.class)
@SpringBootTest
@AutoConfigureMockMvc
@AutoConfigureRestDocs
public class LoginLogoutTest {

    @Autowired
    private MockMvc mockMvc;

    @Test
    public void adminCanLoginLogout() throws Exception {
        mockMvc.perform(formLogin().user(TestConfig.ADMIN_USERNAME).password(TestConfig.PASSWORD))
            .andExpect(status().isOk())
            .andExpect(authenticated().withUsername(TestConfig.ADMIN_USERNAME))
            .andDo(document("login"));

        mockMvc.perform(logout())
            .andExpect(status().isOk())
            .andExpect(unauthenticated())
            .andDo(document("logout"));
    }
}
```

It causes `java.lang.IllegalStateException: REST Docs configuration not found. Did you forget to apply a MockMvcRestDocumentationConfigurer when building the MockMvc instance?` on the line with `document("login")`.

What could be the cause?

**Comment by wilkinsona** [comment]
I can't tell without some more context. Where is the method `formLogin()` defined, for example? If you'd like me to spend some more time investigating, can you please take the time to create a complete and minimal example that reproduces the problem, zip it up, and attach it to this issue?

**Comment by ValtteriL** [comment]
formLogin() is defined in org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestBuilders.formLogin.

Here's an example of a program that reproduces the problem.
[restdocs-formlogin.zip](https://github.com/spring-projects/spring-restdocs/files/3771766/restdocs-formlogin.zip)

**Comment by wilkinsona** [comment]
Thanks for the sample.

The problem is due to a bug or limitation of `SecurityMockMvcRequestBuilders$FormLoginRequestBuilder`. It does not implement `Mergeable` so the default configuration that is set up on the `MockMvc` instance is not applied. Crucially in the case of Spring REST Docs, this means that the `ConfigurerApplyingRequestPostProcessor` that applies the REST Docs context to the request is lost.

Can you please open a [new Spring Security issue](https://github.com/spring-projects/spring-security/issues/new) and comment here with a link to it so that others can follow along?

**Comment by ValtteriL** [comment]
https://github.com/spring-projects/spring-security/issues/7572
