### ISSUE TITLE
Fix dependency on @EnableHypermideaSupport and accept(MediaTypes.HAL_JSON) for passing tests

### ISSUE THREAD

**Issue by diendanyoi54** [spring-projects/spring-restdocs#662]
I have spun my wheels numerous times on multiple projects and typically give up on Hateoas because I always have trouble using it with MockMvc.  I just recently discovered that when the controller is annotated with `@EnableHypermediaSupport(type = EnableHypermediaSupport.HypermediaType.HAL)` and the test includes `mockMvc.perform(post("").accept(MediaTypes.HAL_JSON)` the test passes.  While this may not be a big deal, the solution still works in production without the above, even though the tests fail.  The tests should reflect what actually works when the program runs.

**Comment by wilkinsona** [comment]
Thanks for the report. It's not clear to me how the above relates to Spring REST Docs. Can you please elaborate? A small sample that reproduces the problem you've been facing would be ideal.

**Comment by diendanyoi54** [comment]
I appreciate the quick response.  Here is a link to a demo project https://github.com/diendanyoi54/hateoas-testing-error .  I know it's an old version but I have run into this with newer versions and in Kotlin/Spring projects as well.  If I need to post this in a different repo let me know, wasn't exactly sure where this issue belonged.

**Comment by wilkinsona** [comment]
Thanks for the sample. The problem is caused by the way that you have [set up MockMvc](https://github.com/diendanyoi54/hateoas-testing-error/blob/6e4b4c91a466f3a5fec32eb1c796ed8a1c9b1472/src/test/java/com/example/demo/CustomerControllerTest.java#L36). You're using a standalone controller setup which means that none of the configuration in your application context is used. This is why the behaviour in your tests is not the same as the behaviour at runtime. You either need to make sure that you apply all the necessary configuration to your standalone setup or you need to set up MockMvc using the web application context. I'd recommend the latter and it would look something like this:

```java
    @Autowired
    private WebApplicationContext context;

    @Before public void setup() {
        mockMvc = MockMvcBuilders.webAppContextSetup(context)
                .alwaysDo(prepareJackson(objectMapper))
                .alwaysDo(commonDocumentation())
                .apply(documentationConfiguration(restDocumentation)
                        .uris()
                        .withScheme("http")
                        .withHost("localhost")
                        .withPort(8080)
                        .and().snippets()
                        .withDefaults(curlRequest(), httpRequest(), httpResponse(), requestFields(), responseFields(), pathParameters(),
                                requestParameters(), description(), methodAndPath(), section(), authorization(DEFAULT_AUTHORIZATION)))
                .build();
    }
```

**Comment by diendanyoi54** [comment]
I very much appreciate your quick response and the explanation.  That actually makes perfect sense.  In practice I am using standalone because that was how I first learned how to get around OAuth2 protected endpoints but after a quick search there seems to be a better way now which I'll probably implement as to avoid the standalone server.  Thank you very much for the answer!
