### ISSUE TITLE
Ignored fields still appear in http-request.adoc and request-body.adoc snippets

### ISSUE THREAD

**Issue by ianfp** [spring-projects/spring-restdocs#684]
I have the following (Kotlin) code for generating REST docs using WebTestClient and Spring Rest Docs **v2.0.4**:
```kotlin
    @Test
    fun `POST email`() {
        testClient.post()
            ...
            .expectBody()
            .consumeWith(document("email",
                documentRequestFields(),
                documentResponseFields()))
    }

    private fun documentRequestFields() = relaxedRequestFields(
        fieldWithPath("recipients[].type").type("string")
            .description("TO, CC, or BCC"),
        fieldWithPath("recipients[].address.address").type("string")
            .description("Recipient email address"),
        fieldWithPath("recipients[].address.name").type("string").optional()
            .description("Recipient name"),
        ...

        // ignore convenience getters that are not part of the API
        fieldWithPath("to").ignored(),
        fieldWithPath("cc").ignored(),
        fieldWithPath("bcc").ignored()
    )
```

The `request-fields.adoc` snippet does not include the ignored fields (`to`, `cc`, and `bcc`), which is great. But the `http-request.adoc` and `request-body.adoc` snippets still show them, which will certainly confuse consumers of my API.

The documentation says
> If you do not want to document a field or subsection at all, you can mark it as ignored. This prevents it from appearing in the generated snippet

So I'd expect those fields to be omitted from _all_ snippets.

**Comment by wilkinsona** [comment]
> So I'd expect those fields to be omitted from all snippets.

Given that the documentation says "the", it's not clear why you'd expect the behaviour to apply to all snippets. The use of "the" is intentional as the behaviour only applies to the snippet that the documentation is describing. 

There's no interaction between snippets in REST Docs. In this case, as you have observed, ignoring a field in one snippet has not effect on its presence in any other snippet. If you want to remove the field entirely from the documentation, then you should pre-process the request and/or response before it's documented. You can [provide your own preprocessor](https://docs.spring.io/spring-restdocs/docs/2.0.4.RELEASE/reference/html5/#customizing-requests-and-responses-preprocessors-writing-your-own) to manipulate the request or response body to meet your needs.

**Comment by ianfp** [comment]
Ah, I missed that section heading! Thanks for clarifying.
