### ISSUE TITLE
Ability to post-process a response after it is documented

### ISSUE THREAD

**Issue by wimdeblauwe** [spring-projects/spring-restdocs#685]
I have one case where the response of a call is a very long JSON document that is more or less hardcoded (it is the terms and conditions of that particular website). I would like the ability to truncate the response _after_ the documentation has run.

I know about `ContentModifyingOperationPreprocessor`, but doing something like:

```
Preprocessors.preprocessResponse(new ContentModifyingOperationPreprocessor(new ContentModifier() {
@Override
public byte[] modifyContent(byte[] originalContent, MediaType contentType) {
  if (originalContent.length > 200) {
    return (new String(Arrays.copyOfRange(originalContent, 0, 200), StandardCharsets.UTF_8) + "\n<< REST OF RESPONSE TRUNCATED >>").getBytes(StandardCharsets.UTF_8);
  } else {
    return originalContent;
  }
}
})),
```

results in invalid JSON obviously, so the documentation test fails.

**Comment by wilkinsona** [comment]
You should be able to do anything you want after the documentation snippets have been generated but I think that's out of the scope of REST Docs. For example, with MockMvc you can perform an additional `andDo(ResultHandler)` that truncates the response and then carries on with whatever processing you want to see it in its shorter form:

```java
mockMvc.perform(get("/").accept(MediaType.APPLICATION_JSON))
	.andExpect(status().isOk())
	.andDo(document("example"))
	.andDo((result) -> {
		// Get response content, truncate, and perform further processing
	});
```

Does that give you what you need?

**Comment by wimdeblauwe** [comment]
Not really. I would like the `document` method to check the JSON and make sure all fields are ok like normally, but then truncate the response to generate the actual `http-response.adoc` snippet. This would avoid that my documentation would contain a massive amount of repetitive JSON.

**Comment by wilkinsona** [comment]
Thanks for the clarification. The sounds like pre-processing to me but applied to a single snippet. There's no support for that at the moment, largely because of the consistency that pre-processing for all snippets ensures.

Have you considered truncating the response in such a way that it remains valid JSON? For example, if there's a key-value pair in the response where the value is a very long string, you could truncate that string. Alternatively, if there are a number of identically structured parts of the response, you could limit the number of them. We have [some code](https://github.com/spring-projects/spring-boot/blob/49921d65acd29a9704c2dd54ef405d6654dcb321/spring-boot-project/spring-boot-actuator-autoconfigure/src/test/java/org/springframework/boot/actuate/autoconfigure/endpoint/web/documentation/AbstractEndpointDocumentationTests.java) in Spring Boot's Actuator API documentation that does this where we limit parts of the payload to three entries. I've wondered before if this sort of functionality might be generally useful. It could be added to REST Docs if so.

Another option that you could consider is a custom HTTP response snippet. You could sub-class `org.springframework.restdocs.http.HttpResponseSnippet`, override `createModel(Operation)` and replace the value of the `responseBody` entry in the map with a truncated version.

**Comment by wimdeblauwe** [comment]
I'll look into more detail to that code to truncate the JSON so it remains valid, that might be interesting for my use case.

**Comment by wilkinsona** [comment]
Great. Please let me know how it goes. If it proves useful, we can consider adding some general purpose support to REST Docs.

**Comment by wimdeblauwe** [comment]
I just had a look and unfortunately that limiting code is not "good enough" for my use case. The problem is that I have a bit of optional structure that I would like to show in the example snippet, but there is nothing of the optional stuff in the first 3 items of the array. I would need some way to select specific indexes in the returned array to keep. But that sounds really brittle to me.

I realize now that my original proposal to post-process _after_ the documentation checks would suffer the same problem. Having said that, I still think that the limiting code could be useful to a broader audience, but I guess most people just tweak their mocks to just return some nice data for the documentation and so they don't need it.

**Comment by wilkinsona** [comment]
> but I guess most people just tweak their mocks to just return some nice data for the documentation and so they don't need it.

That's my preference and is largely what I have seen in practice as well. The code in Spring Boot for limiting the response is only used when it's hard to control the data in the response, for example when documenting the actuator's thread dump endpoint.

Until there's demand for limiting what's in a response, I don't think anything should be added to REST Docs. Similarly, if it's possible for you to do what you want with what's currently available, I don't think it's worth adding anything to REST Docs to make it easier.

While brittle due to the structure of your response, does an approach similar to the limiting or a custom HttpResponseSnippet sub-class let you do what you want?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by wimdeblauwe** [comment]
Yes, you can close the issue.
