### ISSUE TITLE
Support for documenting HAL-FORMS templates

### ISSUE THREAD

**Issue by talentedasian** [spring-projects/spring-restdocs#742]
Was support for documenting template attributes in Hal+Forms media type already discussed before and rejected?

**Comment by wilkinsona** [comment]
I don't recall any previous discussion and a search of the issue tracker hasn't found anything either.

I'm not strongly opposed to adding support, although the experimental and proof-of-concept warning in [the spec](https://rwcbook.github.io/hal-forms/) makes me a little wary of implementing an API that would, ideally, remain backwards compatible on top of such a moving target. It'd be interesting to hear how @odrotbohm has got on in this regard with Spring HATEOAS.

**Comment by odrotbohm** [comment]
I guess I still have to clear up my mind on what "documenting the template attributes" actually means. In fact, HAL FORMS basically takes the same structural definitions of the MVC handler methods and adds that to the payload at runtime. It's documentation in machine-readable form already. The templates basically map to the links added (link documentation is already supported) and those map to resources and the payload and response types of the MVC handler methods (also already supported).

@talentedasian – Care to elaborate what you'd like to see here in detail?

**Comment by talentedasian** [comment]
> I guess I still have to clear up my mind on what "documenting the template attributes" actually means. In fact, HAL FORMS basically takes the same structural definitions of the MVC handler methods and adds that to the payload at runtime. It's documentation in machine-readable form already. The templates basically map to the links added (link documentation is already supported) and those map to resources and the payload and response types of the MVC handler methods (also already supported).
> https://docs.ipfs.io/how-to/exchange-files-between-nodes/#exchange-files-between-nodes
> @talentedasian – Care to elaborate what you'd like to see here in detail?

**Comment by talentedasian** [comment]
My bad i misclicked. 

So with documenting links we have the method `linkWithRel`. As for HAL-FORMS templat, there could be something like `linkWithTemplate` or something equivalent that would generate snippets for template attributes.

**Comment by wilkinsona** [comment]
@talentedasian Rather than how it might be implemented, we're more interested at this stage in determining why it should be implemented. As Ollie described above, the `_templates` section is documentation in machine-readable form already. What benefit will there be to users of your API if its documentation describes in detail the `_templates` section of its responses? In your position, I think I would either ignore it or document the entire `_templates` sub-section as providing templates for `HAL-FORMS`-aware clients.

**Comment by talentedasian** [comment]
Yeah I completely agree with the both of you hink I overlooked this one.

**Comment by odrotbohm** [comment]
I guess something that could be valuable though is to be able to describe that templates of a certain name are expected, combined with a bit of plain text to describe the purpose of the template. This is very similar to the ability to describe links that for HAL look up a `$._links.%s` field in the response, verify it's there and then capture some description to be rendered as Asciidoctor table.

The purpose of something like this for templates is that the client developer would know about which templates it can expect to be present under which circumstances so that it knows which one to look up and hand to the HAL FORMS specific template processing logic. I assume that the description would usually point to the bit of documentation that describes the target resource. It's a bit like the link documentation on steroids.
