### ISSUE TITLE
Add ways to improve the table's layout from code

### ISSUE THREAD

**Issue by vicmosin** [spring-projects/spring-restdocs#75]
Let's say we have the following:
```
.andDo(
   RestDocumentation.document("users-list-example")
        .withQueryParameters(
            parameterWithName("filter").description("Type of the users to retrieve. Possible values are `staff` and `customers`")
        )
)
```
this will produce a table with two equal columns each one of them. In this particular cases it would be great to make the first column's width smaller then the second one..

**Comment by wilkinsona** [comment]
Thanks for the suggestion, @vicmosin. This issue is somewhat related to #70 and should probably be tackled at the same time.

In addition to making the column widths configurable, I think there's room to improve the defaults. I've opened #76 to track that.

**Comment by wilkinsona** [comment]
I've looked into this some more, and I no longer think it's something that Spring REST Docs needs to support via its API. Asciidoctor will already let you do this and I don't want to reinvent the wheel.

You can configure the widths of the columns when you include a snippet like so:

```
[cols="1,4"]
include::{snippets}/error-example/response-fields.adoc[]
```

This will split the width of the table so that column 1 uses 20% of the width and column 2 uses 80%.

It's probably worth describing this in the reference docs.

**Comment by vicmosin** [comment]
I totally agree that it's more asciidoctor's issue rather then restdocs. Just didn't know thus syntax. Thank you very much.

**Comment by wilkinsona** [comment]
Reopening to track the update to the reference documentation
