### ISSUE TITLE
Add support for documenting path parameters

### ISSUE THREAD

**Issue by awendland** [spring-projects/spring-restdocs#86]
Is it possible for Spring REST Docs to document variable portions of the path, such as to coincide with the @PathVariable annotation in the Spring Rest Controllers?

**Comment by wilkinsona** [comment]
It's not possible at the moment, but you're not the first to ask. /cc @mminella

**Comment by wilkinsona** [comment]
@awendland @mminella I've been thinking about this a bit and would welcome your input. I'm struggling at the moment to figure out what the API would look like. The problem is that for it to be clear that path parameters were being used, you'd have to do something like this:

```java
mockMvc.perform(get("/{foo}/{bar}", "one", "two"))
```

The `get` call creates a `MockHttpServletRequestBuilder`, but its constructor immediately turns the url template and parameters into an instance of `UriComponents`, At this point the information in the template (that there are two parameters named foo and bar) is lost so there's no way for Spring REST Docs to know what should be documented.

If we can figure out what we'd like the Spring REST Docs API to look like, perhaps we can then work with @rstoyanchev to make whatever changes may be required in MockMvc.

**Comment by awendland** [comment]
@wilkinsona I like that form of the URL because it is consistent with the `@RequestMapping` definition for Path Variables. Is it possible to modify the `MockHttpServletRequestBuilder` in a way for Spring REST Docs to retrieve it prior to modification? Or would their need to be some Spring REST Docs wrapper around the call, such as
```java
mockMvc.perform(get(variableRequest("/{foo}/{bar}", "one", "two")))
```

**Comment by mminella** [comment]
I'll be the first to admit that this corner of the framework is a bit of magic to me still.  However, what about something like:
```
RestDocumentationHandler handler = document("documented-foo");
mockMvc.perform(getDocumentedPath("/{foo}/{bar}", "one", "two", handler)).andDo(handler...
```
Obviously you could also have `postDocumentedPath`, etc.  This would allow you to intercept the values prior to modification and then delegate to the original `get` method.  While it's not quite as elegant as the original piece, it would work and is only needed for path variables.

**Comment by awendland** [comment]
This could also be utilized to produce another snippet such as `GET /user/groups` so that the endpoint URL can be easily included in the documentation. Then people could use something along the lines of 

```adoc
include::{snippets}/groups-get/endpoint.adoc[]
```

**Comment by marceloverdijk** [comment]
I also like the format

    mockMvc.perform(get(variableRequest("/{foo}/{bar}", "one", "two")))

as @awendland already pointed out this exactly what we have in request mappings.

To be honest this is also the approach I use in junit tests. Very useful if you e.g. have some kind of Paths class with the actual paths as static fields shared between main and test code.

**Comment by marceloverdijk** [comment]
But documenting path parameters is a real must imo.

**Comment by wilkinsona** [comment]
@awendland @mminella Thanks for the suggestions

**Comment by AGoliath** [comment]
+1 for getDocumentedPath

I was about to start looking into it, but stopped once I saw how get merges path parameters.
Adding a getDocumentedPath() would allow the change to be only in spring-restdocs and no need for changing mock-mvc If I´m not mistaken, so that would be a clear plus for me.

**Comment by rozhok** [comment]
Absolutely awesome! Thank you!
