### ISSUE TITLE
Missing queryParam handling in MockMvcRequestConverter for HEAD requests

### ISSUE THREAD

**Issue by HaVonTe1** [spring-projects/spring-restdocs#888]
I stumpled over a n issue when documenting a HEAD Request with a QueryParam.

Example:

`   
 this.mockMvc
        .perform(head("/mydomian").param("myparam", "test"))
        .andExpect(status().isConflict())
        .andDo(document("test_of_head_with_query_param", queryParameters(parameterWithName("myparam").description("some desc"))))
        .andReturn();`

I get the Error: 
org.springframework.restdocs.snippet.SnippetException: Query parameters with the following names were not found in the request: [myparam]

I think the bug sits here:
QueryParams are only considered for GET Requests. 

https://github.com/spring-projects/spring-restdocs/blob/main/spring-restdocs-mockmvc/src/main/java/org/springframework/restdocs/mockmvc/MockMvcRequestConverter.java#L83

**Comment by Hank-Choi** [comment]
I am experiencing the same issue

Example:
```java
mvc.perform(
		delete("/example")
			.contentType(MediaType.APPLICATION_JSON)
			.param("param", "test")
	)
	.andExpect(status().isOk())
	.andDo(document(queryParameters(parameterWithName("param").description("desc"))));
	
// org.springframework.restdocs.snippet.SnippetException: Query parameters with the following names were not found in the request: [param]
```

**Comment by wilkinsona** [comment]
Thanks, both. What version of REST Docs are you using and was it working correctly with earlier versions? I'm wondering if this is a regression (most likely introduced in https://github.com/spring-projects/spring-restdocs/commit/f5a629af34b461cd6a1ea691c47deba9b037c30b) or a longer-standing problem.

**Comment by Hank-Choi** [comment]
@wilkinsona 
Thanks for response. 
I am using spring-restdocs-mockmvc 3.0.0 version and it worked correctly when using `requestParameters` method

**Comment by wilkinsona** [comment]
On closer inspection, I am not sure that we should try to make this work.

@Hank-Choi @HaVonTe1, you're both using `MockMvc`'s `param` method. From its javadoc:

> In the Servlet API, a request parameter may be parsed from the query string and/or from the body of an `application/x-www-form-urlencoded` request. This method simply adds to the request parameter map

Adding directly to the request parameter map means that REST Docs cannot tell how you intend users of your API to send the parameter. Should it by in the query string or should it be in the request body? This didn't matter so much in earlier versions of REST Docs as it (incorrectly) documented query parameters and form parameters together as request parameters. Now that this support has been replaced, the separation is more important. Please update your tests to use `queryParam` rather than `param`. This will ensure that the parameter is included in the request's query string allowing REST Docs to tell exactly how you intend your API's clients to send the parameter.

I've updated the wiki to add this guidance to [the relevant section of the release notes](https://github.com/spring-projects/spring-restdocs/wiki/Spring-REST-Docs-3.0-Release-Notes#request-parameters-support-removed).

**Comment by HaVonTe1** [comment]
Thx. .queryParam works perfectly.
