### ISSUE TITLE
Easier navigation through resource/endpoint url's [idea]

### ISSUE THREAD

**Issue by marceloverdijk** [spring-projects/spring-restdocs#90]
In a big project we use `asciidoctor` for documenting our REST services.
We are actually not (yet) using `spring-restdocs` but basically the output (layout) is the same, only we document the snippets manually instead of generating them.

As we have a big API catalog one of the remarks we get is that it is difficult to navigate to or find the documentation for a given endpoint.
We already tried a `:toc:` on the right side but as there are to many services this is also not really workable.

I think for large projects also using `spring-restdocs` will give the same problem.

I don't know if this would be possible at all but maybe a dropdown with all resources/endpoints in the header could help.
Just like http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/ has a search functionality in the footer.

**Comment by wilkinsona** [comment]
I like the idea, but I think it's outside of this project's scope.

Spring REST Docs deliberately tries to avoid doing anything that would limit your options when it comes laying out and formatting the documentation. That's why it generates snippets that you can then include in your Asciidoc. You're free to structure that Asciidoc as you see fit and also have a huge amount of control over the layout/structure/etc of the HTML that's generated. Take a look at Asciidoctor's [support for custom themes](http://asciidoctor.org/docs/user-manual/#custom-themes). There may already be one that does what you want.
