### ISSUE TITLE
Support for pretty printing request bodies (modifyRequest?)

### ISSUE THREAD

**Issue by marceloverdijk** [spring-projects/spring-restdocs#91]
With `modifyResponseTo(prettyPrintContent())` the response bodies can be pretty printed.

Is there support to do something similar for request bodies?

**Comment by wilkinsona** [comment]
There isn't, because I'm not sure that it's necessary. When you're writing the tests, you have complete control over the request body so you can format it before making the request. For example, if you're using a Jackson `ObjectMapper`, you can enable its pretty printing like this:

```java
objectMapper.configure(SerializationFeature.INDENT_OUTPUT, true);
```

You'd only need Spring REST docs to do the formatting in a post-processor if, for some reason, you service can't consume pretty-printed content. That doesn't seem likely, and I wouldn't want to encourage people to write such services... That said, you might be interested in #84. It talks about hiding request headers from the documentation. Those headers may be required by the service but, for whatever reason, you don't want them to appear in a particular snippet. It's likely that Spring REST Docs will support something along those lines in the future.

**Comment by marceloverdijk** [comment]
Yes, I'm using a second `ObjectMapper` now to do this.
Another option is indeed to change the @Autowired ObjectMapper or configure it differently when running in 'documentation' mode.
This would also give the benefit for more easily change the pretty print for response bodies.

**Comment by marceloverdijk** [comment]
For reference, this is what I was using now:

    @Autowired
    protected ObjectMapper objectMapper;

    @Test
    public void create_example() throws Exception {
        Input input = ..;
        mockMvc.perform(post("some-url")
                .accept(APPLICATION_JSON)
                .contentType(APPLICATION_JSON)
                .content(prettyPrint(objectMapper.writeValueAsString(input))))

    private String prettyPrint(String original) throws IOException {
        ObjectMapper mapper = new ObjectMapper().configure(
                SerializationFeature.INDENT_OUTPUT, true);
        return mapper.writeValueAsString(mapper.readTree(original));
    }

**Comment by NoICE** [comment]
I'm using this - which will format all requests and responses during the test run:

```kotlin
class XXXTest {

    @Autowired
    private lateinit var objectMapper: ObjectMapper

    @Before
    fun setup() {
        // pretty print jsons so we are getting nice request and response bodies
        objectMapper.configure(SerializationFeature.INDENT_OUTPUT, true)
    }
}
```

**Comment by Sarvesh-D** [comment]
As per docs for `2.0.4` spring rest docs can pretty print request via `prettyPrint()` processor. 
```
this.mockMvc = MockMvcBuilders.webAppContextSetup(ctx)
                                      .alwaysDo(JacksonResultHandlers.prepareJackson(mapper))
                                      .apply(MockMvcRestDocumentation.documentationConfiguration(restDocumentation).operationPreprocessors().withRequestDefaults(prettyPrint());
```
This works for me.
